name: Build SecurityCheck DLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile with MSVC
      run: |
        cl /LD SecurityCheck.cpp /link /OUT:SecurityCheck.dll user32.lib kernel32.lib advapi32.lib /nologo

    - name: Verify DLL
      run: |
        if (Test-Path SecurityCheck.dll) {
          Write-Host "编译成功！"
          Get-ChildItem SecurityCheck.dll
        } else {
          Write-Host "编译失败：DLL文件未生成"
          exit 1
        }

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecurityCheck-DLL
        path: SecurityCheck.dll
